#ifndef __REG_H
#define __REG_H
#include "stdint.h"

#define __REG(x) *((volatile uint32_t*)(x))

/**************register base address***************/
#define RCC_BASE        (0x40023800UL)
#define GPIOA_BASE      (0x40020000UL)
#define USB_OTG_FS_BASE (0x50000000UL)
#define USART2_BASE     (0x40004400UL)
#define GPIOC_BASE      (0x40020800UL)
#define GPIOD_BASE      (0x40020C00UL)
/***********RCC related***************/
/************CR reset value: 0x0000 xx83************************/
#define RCC_CR (__REG(RCC_BASE + 0x00))
#define HSE_ON (1 << 16)
#define PLL_ON (1 << 24)

#define RCC_CFGR (__REG(RCC_BASE + 0x08))
#define SWHSI    (0 << 0)
#define SWHSE    (1 << 0)
#define SWPLL    (2 << 0)
/************PLL config register reset value: 0x2400
 * 3010************************/
/********2<=PLLQ<=15 ;PLLP 2,4,6,8;
 * 50<=PLLN<=432;2<=PLLM<=63*******************************************/
#define RCC_PLLCFGR  (__REG(RCC_BASE + 0x04))
#define PLLQ(x)      (x << 24)
#define PLLM(x)      (x << 0)
#define PLLN(x)      (x << 6)
#define PLLP(x)      (((x >> 1) - 1) << 16)
#define RCC_AHB1_ENR ((__REG(RCC_BASE + 0x30)))
#define RCC_AHB2_ENR ((__REG(RCC_BASE + 0x34)))
#define RCC_AHB3_ENR ((__REG(RCC_BASE + 0x38)))
#define RCC_APB1_ENR ((__REG(RCC_BASE + 0x40)))
#define RCC_APB2_ENR ((__REG(RCC_BASE + 0x44)))

/************uart2 for debug*********************/
#define USART2_SR   (__REG(USART2_BASE + 0x00))
#define USART2_DR   (__REG(USART2_BASE + 0x04))
#define USART2_BRR  (__REG(USART2_BASE + 0x08))
#define USART2_CR1  (__REG(USART2_BASE + 0x0c))
#define USART2_CR2  (__REG(USART2_BASE + 0x10))
#define USART2_CR3  (__REG(USART2_BASE + 0x14))
#define USART2_GTPR (__REG(USART2_BASE + 0x18))

/**************GPIO related**************************/
#define GPIO_MODER(GPIO_BASE)   (__REG(GPIO_BASE + 0x00))
#define GPIO_OTYPER(GPIO_BASE)  (__REG(GPIO_BASE + 0x04))
#define GPIO_OSPEEDR(GPIO_BASE) (__REG(GPIO_BASE + 0x08))
#define GPIO_PUPDR(GPIO_BASE)   (__REG(GPIO_BASE + 0x0c))
#define GPIO_IDR(GPIO_BASE)     (__REG(GPIO_BASE + 0x10))
#define GPIO_ODR(GPIO_BASE)     (__REG(GPIO_BASE + 0x14))
#define GPIO_BSRR(GPIO_BASE)    (__REG(GPIO_BASE + 0x18))
#define GPIO_LCKR(GPIO_BASE)    (__REG(GPIO_BASE + 0x1C))
#define GPIO_AFRL(GPIO_BASE)    (__REG(GPIO_BASE + 0x20))
#define GPIO_AFRH(GPIO_BASE)    (__REG(GPIO_BASE + 0x24))

/*************************USB OTG_FS related*******************************/

#define FS_OTGCTL     (__REG(USB_OTG_FS_BASE + 0x000))
#define FS_OTGINT     (__REG(USB_OTG_FS_BASE + 0x004))
#define FS_AHBCFG     (__REG(USB_OTG_FS_BASE + 0x008))
#define FS_USBCFG     (__REG(USB_OTG_FS_BASE + 0x00C))
#define FS_RSTCTL     (__REG(USB_OTG_FS_BASE + 0x010))
#define FS_INTSTS     (__REG(USB_OTG_FS_BASE + 0x014))
#define FS_INTMSK     (__REG(USB_OTG_FS_BASE + 0x018))
#define FS_RXSTSR     (__REG(USB_OTG_FS_BASE + 0x01C))
#define FS_RXSTSPR    (__REG(USB_OTG_FS_BASE + 0x020))
#define FS_RXFSIZ     (__REG(USB_OTG_FS_BASE + 0x024))
#define FS_HNPTXFSIZ  (__REG(USB_OTG_FS_BASE + 0x028))
#define FS_HNPTXSTS   (__REG(USB_OTG_FS_BASE + 0x02C))
#define FS_GCCFG      (__REG(USB_OTG_FS_BASE + 0x038))
#define FS_CID        (__REG(USB_OTG_FS_BASE + 0x03C))
#define FS_HPTXFSIZ   (__REG(USB_OTG_FS_BASE + 0x100))
#define FS_DIEPTXF1   (__REG(USB_OTG_FS_BASE + 0x104))
#define FS_DIEPTXF2   (__REG(USB_OTG_FS_BASE + 0x108))
#define FS_DIEPTXF3   (__REG(USB_OTG_FS_BASE + 0x10C))
#define FS_HCFG       (__REG(USB_OTG_FS_BASE + 0x400))
#define FS_HFIR       (__REG(USB_OTG_FS_BASE + 0x404))
#define FS_HFNUM      (__REG(USB_OTG_FS_BASE + 0x408))
#define FS_HPTXSTS    (__REG(USB_OTG_FS_BASE + 0x410))
#define FS_HAINT      (__REG(USB_OTG_FS_BASE + 0x414))
#define FS_HAINTMSK   (__REG(USB_OTG_FS_BASE + 0x418))
#define FS_HPRT       (__REG(USB_OTG_FS_BASE + 0x440))
#define FS_HCCHAR0    (__REG(USB_OTG_FS_BASE + 0x500))
#define FS_HCCHAR1    (__REG(USB_OTG_FS_BASE + 0x520))
#define FS_HCCHAR2    (__REG(USB_OTG_FS_BASE + 0x540))
#define FS_HCCHAR3    (__REG(USB_OTG_FS_BASE + 0x560))
#define FS_HCCHAR4    (__REG(USB_OTG_FS_BASE + 0x580))
#define FS_HCCHAR5    (__REG(USB_OTG_FS_BASE + 0x5A0))
#define FS_HCCHAR6    (__REG(USB_OTG_FS_BASE + 0x5C0))
#define FS_HCCHAR7    (__REG(USB_OTG_FS_BASE + 0x5E0))
#define FS_HCINT0     (__REG(USB_OTG_FS_BASE + 0x508))
#define FS_HCINT1     (__REG(USB_OTG_FS_BASE + 0x528))
#define FS_HCINT2     (__REG(USB_OTG_FS_BASE + 0x548))
#define FS_HCINT3     (__REG(USB_OTG_FS_BASE + 0x568))
#define FS_HCINT4     (__REG(USB_OTG_FS_BASE + 0x588))
#define FS_HCINT5     (__REG(USB_OTG_FS_BASE + 0x5A8))
#define FS_HCINT6     (__REG(USB_OTG_FS_BASE + 0x5C8))
#define FS_HCINT7     (__REG(USB_OTG_FS_BASE + 0x5E8))
#define FS_HCINTMSK0  (__REG(USB_OTG_FS_BASE + 0x50C))
#define FS_HCINTMSK1  (__REG(USB_OTG_FS_BASE + 0x52C))
#define FS_HCINTMSK2  (__REG(USB_OTG_FS_BASE + 0x54C))
#define FS_HCINTMSK3  (__REG(USB_OTG_FS_BASE + 0x56C))
#define FS_HCINTMSK4  (__REG(USB_OTG_FS_BASE + 0x58C))
#define FS_HCINTMSK5  (__REG(USB_OTG_FS_BASE + 0x5AC))
#define FS_HCINTMSK6  (__REG(USB_OTG_FS_BASE + 0x5CC))
#define FS_HCINTMSK7  (__REG(USB_OTG_FS_BASE + 0x5EC))
#define FS_HCTSIZ0    (__REG(USB_OTG_FS_BASE + 0x510))
#define FS_HCTSIZ1    (__REG(USB_OTG_FS_BASE + 0x530))
#define FS_HCTSIZ2    (__REG(USB_OTG_FS_BASE + 0x550))
#define FS_HCTSIZ3    (__REG(USB_OTG_FS_BASE + 0x570))
#define FS_HCTSIZ4    (__REG(USB_OTG_FS_BASE + 0x590))
#define FS_HCTSIZ5    (__REG(USB_OTG_FS_BASE + 0x5B0))
#define FS_HCTSIZ6    (__REG(USB_OTG_FS_BASE + 0x5D0))
#define FS_HCTSIZ7    (__REG(USB_OTG_FS_BASE + 0x5F0))
#define FS_DCFG       (__REG(USB_OTG_FS_BASE + 0x800))
#define FS_DCTL       (__REG(USB_OTG_FS_BASE + 0x804))
#define FS_DSTS       (__REG(USB_OTG_FS_BASE + 0x808))
#define FS_DIEPMSK    (__REG(USB_OTG_FS_BASE + 0x810))
#define FS_DOEPMSK    (__REG(USB_OTG_FS_BASE + 0x814))
#define FS_DAINT      (__REG(USB_OTG_FS_BASE + 0x818))
#define FS_DAINTMSK   (__REG(USB_OTG_FS_BASE + 0x81C))
#define FS_DVBUSDIS   (__REG(USB_OTG_FS_BASE + 0x828))
#define FS_DVBUSPULSE (__REG(USB_OTG_FS_BASE + 0x82C))
#define FS_DIEPEMPMSK (__REG(USB_OTG_FS_BASE + 0x834))
#define FS_DIEPCTL0   (__REG(USB_OTG_FS_BASE + 0x900))
#define FS_DTXFSTS0   (__REG(USB_OTG_FS_BASE + 0x918))
#define FS_DIEPCTL1   (__REG(USB_OTG_FS_BASE + 0x920))
#define FS_DTXFSTS1   (__REG(USB_OTG_FS_BASE + 0x938))
#define FS_DIEPCTL2   (__REG(USB_OTG_FS_BASE + 0x940))
#define FS_DTXFSTS2   (__REG(USB_OTG_FS_BASE + 0x958))
#define FS_DIEPCTL3   (__REG(USB_OTG_FS_BASE + 0x960))
#define FS_DTXFSTS3   (__REG(USB_OTG_FS_BASE + 0x978))
#define FS_DOEPCTL0   (__REG(USB_OTG_FS_BASE + 0xB00))
#define FS_DOEPCTL1   (__REG(USB_OTG_FS_BASE + 0xB20))
#define FS_DOEPCTL2   (__REG(USB_OTG_FS_BASE + 0xB40))
#define FS_DOEPCTL3   (__REG(USB_OTG_FS_BASE + 0xB60))
#define FS_DIEPINT0   (__REG(USB_OTG_FS_BASE + 0x908))
#define FS_DIEPINT1   (__REG(USB_OTG_FS_BASE + 0x928))
#define FS_DIEPINT2   (__REG(USB_OTG_FS_BASE + 0x948))
#define FS_DIEPINT3   (__REG(USB_OTG_FS_BASE + 0x968))
#define FS_DOEPINT0   (__REG(USB_OTG_FS_BASE + 0xB08))
#define FS_DOEPINT1   (__REG(USB_OTG_FS_BASE + 0xB28))
#define FS_DOEPINT2   (__REG(USB_OTG_FS_BASE + 0xB48))
#define FS_DOEPINT3   (__REG(USB_OTG_FS_BASE + 0xB68))
#define FS_DIEPTSIZ0  (__REG(USB_OTG_FS_BASE + 0x910))
#define FS_DIEPTSIZ1  (__REG(USB_OTG_FS_BASE + 0x930))
#define FS_DIEPTSIZ2  (__REG(USB_OTG_FS_BASE + 0x950))
#define FS_DIEPTSIZ3  (__REG(USB_OTG_FS_BASE + 0x970))
#define FS_DOEPTSIZ0  (__REG(USB_OTG_FS_BASE + 0xB10))
#define FS_DOEPTSIZ1  (__REG(USB_OTG_FS_BASE + 0xB30))
#define FS_DOEPTSIZ2  (__REG(USB_OTG_FS_BASE + 0xB50))
#define FS_DOEPTSIZ3  (__REG(USB_OTG_FS_BASE + 0xB70))
#define FS_PCGCTL     (__REG(USB_OTG_FS_BASE + 0xE00))

#endif
